export const ROUTE = {
  HOME: "/",
  LOGIN: "/login",
  SIGNUP: "/sign-up",
  AUTH: "/auth",
  CLASS: "/class",
  CLASS_EDIT: "/class-edit",
  STUDENT: "/student",
  STUDENTPERSONAL: "/student-personal",
  PLAN: "/plan",
  MAIN: "/main",
  ROLLCALL: "/rollcall",
  PROFILE: "/profile",
  IMPORT: "/import",
};